logging:
  file: ${logdir:logs}/MusicLibraryBoot.log
  level:
    dk.purplegreen: DEBUG
    org.springframework.web: ERROR
    org.hibernate: ERROR
server:
  servlet:
    context-path: /MusicLibraryBoot
    
    
 